IF(TIMER)
add_definitions(-DTIMER=1)
message("[${PROJECT_NAME}]: Timer enabled")
ELSE()
message("[${PROJECT_NAME}]: Timer Disabled")
ENDIF()

IF(TESTING)
add_definitions(-DTESTING=1)
message("[${PROJECT_NAME}]: Testing Output enabled")
ELSE()
message("[${PROJECT_NAME}]: Testing Output disabled")
ENDIF()